require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-permissions/scripts/setup'
setup_permissions([
  'AppTrackingTransparency',
  'LocationAlways',
  'LocationWhenInUse'
])
platform :ios, '13.0'

target 'My_Poppins' do
   # React Native Maps dependencies
  #  permissions_path = '../node_modules/react-native-permissions/ios'
   pod 'react-native-maps', path: '../node_modules/react-native-maps'
   pod 'react-native-google-maps', path: '../node_modules/react-native-maps'
  #  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  #  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  #  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
   pod 'GoogleMaps'
   pod 'Google-Maps-iOS-Utils'
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'My_PoppinsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end